### ISSUE TITLE
Fails on PHP 7.4? Or with new Monolog? (very simple fix, just add void to write array)

### ISSUE THREAD

**Issue by bbruman** [KarelWintersky/monolog-pdo-handler#6]
On `PHP 7.4`.  Current latest monolog at `Monolog 2.1.1`.

Can't do anything with library, as this error haulted script when initializing:

```PHP Fatal error: Declaration of KarelWintersky\Monolog\KWPDOHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in /C:/....../vendor/karelwintersky/monolog-pdo-handler/src/KWPDOHandler.php on line 317```

This was extremely simple to fix.  I just added the `void` type to the `write()` function on `Line 317` of `KWPDOHandler.php`

before, not working:
`protected function write(array $record)
    {`

after, working:
`protected function write(array $record): void
    {`

**Comment by KarelWintersky** [comment]
Can you make pull request? I'll accept it quickly ASAP ;)

**Comment by l0rb** [comment]
While this is fixed in the code, it needs a release to turn up in composer
