### ISSUE TITLE
PostgreSQL uses different query syntax

### ISSUE THREAD

**Issue by stevevance** [KarelWintersky/monolog-pdo-handler#7]
Would you accept a pull request that modifies the following?

- PostgreSQL doesn't allow ```` ` ```` (the backtick). It uses `"` double quotes around relation (table) and field names. 
- Change the field types. The `timestamp` field doesn't work as written, and I would change the `channel` from `VARCHAR(64)` to `TEXT` (I don't think the text field should be limited to 64 characters, unless this is a Monolog or PSR standard)
- Modify how the indexes are made (use CREATE INDEX IF NOT EXISTS)

I would also add a formatter for JSON fields.

**Comment by KarelWintersky** [comment]
Welcome :)

**Comment by KarelWintersky** [comment]
Updated to version 0.4 

waiting for your PR :)

**Comment by stevevance** [comment]
I created a PR https://github.com/KarelWintersky/monolog-pdo-handler/pull/8

**Comment by KarelWintersky** [comment]
Accepted

**Comment by KarelWintersky** [comment]
@stevevance , version 0.5 released

**Comment by stevevance** [comment]
very cool, thank you
